apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:1.29.3
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: nginx-storage
          mountPath: "/data"
  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: pvc-hostpat
