image: maven:3.8.4-openjdk-17

stages:
  - compile
  - test
  - build
  # - sonarqube-analysis
  - containerize

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    IMAGE_NAME: owahed1/demo-app
    IMAGE_TAG: boardgame-java-app-0.0.2
    DOCKER_HOST: tcp://docker:2376
#   SONAR_HOST_URL: http://3.110.31.223:9000
#   SONAR_LOGIN: ${SONAR_LOGIN}

compile-job:
  stage: compile
  script:
    - echo "Building the application..."
    - mvn compile
  # tags:
  #   - self-hosted

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
  # tags:
  #   - self-hosted

build-job:
  stage: build
  script:
    - echo "Packaging the application..."
    - mvn package
  artifacts:
     paths:
       - target/*.jar
  # tags:
  #   - self-hosted

# sonar-code-check-job:
#   stage: sonarqube-analysis
#   script:
#     - mvn sonar:sonar -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_LOGIN}
#   tags:
#     - self-hosted

docker-image-push-job:
  image: docker:27.1.1
  services:
    - docker:27.1.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  stage: containerize
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - unset DOCKER_HOST
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  # tags:
  #   - self-hosted
