version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass       # change if you want
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    restart: always
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 64M                   # fixes 2MB upload error
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
